### ISSUE TITLE
Predefined route for generating new token

### ISSUE THREAD

**Issue by tienkhoi** [chrisbjr/api-guard#10]
I think the url for getting a new token should be
http://localhost:8000/apiguard/generate(according to the source code)
instead of
$ curl -X POST http://localhost:8000/apiguard/api_key as the document says.

**Comment by HCKgit** [comment]
####api-guard on nginx works... on XAMPP I am getting 404 :|
I made a post on [laravel.io](http://laravel.io/forum/01-05-2015-api-guard-on-nginx-works-on-xampp-i-am-getting-404-i-uses-windows-7)

**Comment by MichaelObi** [comment]
Having the sam e issue of not getting the transformers directory on laravel 5

**Comment by brajmohans** [comment]
I am also not getting transformers directory, So Chrisbjr\ApiGuard\Transformers\ApiKeyTransformer class not found
