### ISSUE TITLE
Transformer class not found

### ISSUE THREAD

**Issue by bradsapp** [chrisbjr/api-guard#100]
I'm working on the example from the documentation using Laravel 4.2 but I always get a BookTransformer class not found error. What am I missing from the documentation?

`use Chrisbjr\ApiGuard\ApiGuardController;

class BooksController extends ApiGuardController
{
    public function all()
    {
        $books = Book::all();

        return $this->response->withCollection($books, new BookTransformer);
    }`

**Comment by gholol** [comment]
You have to write  your own transformers yourself. It's just an example.

http://fractal.thephpleague.com/transformers/

**Comment by chrisbjr** [comment]
@gholol is right - I'll make sure there is a bit of info and some links regarding transformers in the readme on the next releases.

**Comment by bradsapp** [comment]
Thanks chrisbjr for the response and also gholol.
