### ISSUE TITLE
Class 'ApiGuardAuth' not found

### ISSUE THREAD

**Issue by robotNIXX** [chrisbjr/api-guard#101]
Hello. Thank you for your work. I tried to use the last commit from the branch and got the error message:
`FatalErrorException in ApiGuard.php line 99:
Class 'ApiGuardAuth' not found`

I changed the code to include the  ApiGuardAuth from the main directory of package, but got the next error message:
`ErrorException in ApiGuard.php line 99:
Non-static method Chrisbjr\ApiGuard\ApiGuardAuth::authenticate() should not be called statically, assuming $this from incompatible context`

What should I change? Thank you.
Best regards,
Andrey Baranov

**Comment by robotNIXX** [comment]
For the first issue I found the reason - I left the old config file.

**Comment by robotNIXX** [comment]
So, there is no issues, but I got $this->user = null in my Controller

**Comment by robotNIXX** [comment]
Thanks, I found the issue. My mistake.

**Comment by chrisbjr** [comment]
Hi @robotNIXX thanks for trying out the master branch. I haven't included instructions in the readme yet but you have to add the following in the `aliases` section of your `config/app.php` file:

`'ApiGuardAuth' => \Chrisbjr\ApiGuard\Facades\ApiGuardAuth::class,`

Please note that there might be some further changes and optimizations to the master branch and I'll be tagging this release as `v3.1.0`

**Comment by robotNIXX** [comment]
Hello, @chrisbjr. Thank you very much!
