### ISSUE TITLE
apache_request_headers() undefined

### ISSUE THREAD

**Issue by maksymkhar** [chrisbjr/api-guard#104]
When I extend ApiGuardController in my controller I get this error.

`FatalThrowableError in ApiGuard.php line 195: Fatal error: Call to undefined function Chrisbjr\ApiGuard\Http\Middleware\apache_request_headers()`

Not all PHP configs support **apache_request_headers**. Are you planning fix it?

[PHP docs](http://php.net/manual/en/function.apache-request-headers.php)

**Comment by chrisbjr** [comment]
Hi @maksymkhar try using the dev-master branch instead for the meantime

**Comment by maksymkhar** [comment]
Hi @chrisbjr, thank you for the reply.

I tried the dev-master branch but i get the following error:

`FatalThrowableError in ApiGuardController.php line 38: Fatal error: Class 'ApiGuardAuth' not found`

**Comment by maksymkhar** [comment]
I tried add aliase in the `app.php` file following this issue: #101 and I get this error:

`FatalThrowableError in ApiGuardAuth.php line 14: Type error: Argument 1 passed to Chrisbjr\ApiGuard\ApiGuardAuth::__construct() must be an instance of Chrisbjr\ApiGuard\Contracts\Providers\Auth, null given, called in /home/vagrant/Code/NotiApp/vendor/chrisbjr/api-guard/src/Providers/ApiGuardServiceProvider.php on line 49`

Any idea?

**Comment by ivannovak** [comment]
@maksymkhar - have a look at the difference between your config/apigaurd.php add vendor/chrisbjr/api-guard/config/apiguard.php and reconcile.

**Comment by maksymkhar** [comment]
@ivannovak Awesome, that's it! Thanks!!

**Comment by chrisbjr** [comment]
Hi all, please use 3.1.x
