### ISSUE TITLE
Getting Session Auth error when using ApiGuard 

### ISSUE THREAD

**Issue by newelement** [chrisbjr/api-guard#105]
Greetings,

I'm getting this error on v3.0.3. This happens when I do an actual test of my api using the X-Authentication header

Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given

**Comment by mShahidAslam** [comment]
I had the same problem and solved it by extending User model with `Authenticatable`.

Extend your User model with this class. It should look like following:
`use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
// Your $fillable and $hidden arrays.
}`

Hope, it will solve your problem.

**Comment by chrisbjr** [comment]
Hi @newelement I've just tagged v3.1.0 - please use that instead of 3.0.3.

Thanks
