### ISSUE TITLE
Api Guard contructor error

### ISSUE THREAD

**Issue by astritzeqiri** [chrisbjr/api-guard#106]
When i make a request to my contoller:
i get this:

Argument 1 passed to Chrisbjr\ApiGuard\ApiGuardAuth::__construct() must be an instance of Chrisbjr\ApiGuard\Contracts\Providers\Auth, null given, called in E:\xampp\xampp\htdocs\2016\api\vendor\chrisbjr\api-guard\src\Providers\ApiGuardServiceProvider.php on line 49 and defined

P.S. I am using laravel 5.2
![untitled-1](https://cloud.githubusercontent.com/assets/8720176/13435897/de42e168-dfdc-11e5-9c13-ab4e8e9fc0c4.jpg)

**Comment by sungitly** [comment]
I just got the same problem and solved it by the following steps.

1. update your project config/apiguard.php according to the same file in api-guard
2. add new alias to app.php
```php
'ApiGuardAuth' => Chrisbjr\ApiGuard\Facades\ApiGuardAuth::class
```

**Comment by chrisbjr** [comment]
Hi, @astritzeqiri instructions for this can now be found in the README of v3.1.x
