### ISSUE TITLE
Api token expiry and refresh ?

### ISSUE THREAD

**Issue by brajmohans** [chrisbjr/api-guard#107]
It seems like token never expires. I think a token must be expired if user is idle for say 10 mins.
Moreover if a user is logged in from multiple clients like from multiple mobiles apps then wouldn't the token will conflict ?

**Comment by chrisbjr** [comment]
If you want a token expiry mechanism - you should switch over to JWT. JWT has designed a more standard approach for this. This library provides static API keys that you can generate and manipulate through the database which is the use case for some.
