### ISSUE TITLE
Access apiKey instance from Controller

### ISSUE THREAD

**Issue by grcasanova** [chrisbjr/api-guard#109]
I am trying to retrieve user details from a controller using:

`$this->apiKey->user_id`

but I keep getting 

> Trying to get property of non-object

The controller class is extending ApiGuardController correctly and the authorization middleware perfectly works.

**Comment by mShahidAslam** [comment]
I had the same issue and solved it by following the [Muya's Blog](https://blog.muya.co.ke/api-guard-laravel-5-2/).
I also changed the apiguard.php file according to the  api-guard/config/apiguard.php of this repo.
Finally access the user using: `$user = Auth::user();`

Hope, it will solve your issue too.

**Comment by grcasanova** [comment]
Not working at all, the "dev" branch has still lots of issues to be solved.

**Comment by mShahidAslam** [comment]
One more thing I did was to extend the User model with `Authenticatable`.

After performing above steps, did you get the same error or any other?

**Comment by grcasanova** [comment]
The dev branch has a way too many errors to be used, still relying on methods from 5.1 and incompatible methods. Anyway, since Laravel 5.2 ships with api authentication middleware, I decided to drop this buggy package.
