### ISSUE TITLE
Getting error in fresh installation BooksController

### ISSUE THREAD

**Issue by adnanmayo** [chrisbjr/api-guard#111]
Hello thanks in advance i am using this package and it realy suit my project what i am building...after updating i am getting these error on all request

   ErrorException in ApiGuardAuth.php line 14:
Argument 1 passed to Chrisbjr\ApiGuard\ApiGuardAuth::__construct() must be an instance of Chrisbjr\ApiGuard\Contracts\Providers\Auth, null given, called in E:\xammp\htdocs\vox\didww\vendor\chrisbjr\api-guard\src\Providers\ApiGuardServiceProvider.php on line 49 and defined

any suggestion?

**Comment by sashahilton00** [comment]
+1 Also getting this error, am just trying to pin down what is causing it at the moment.

**Comment by sashahilton00** [comment]
The error was introduced between 3.0.3 and 3.1.0

**Comment by chrisbjr** [comment]
Hi @sashahilton00 sorry, wasn't able to include the additional instruction in the readme:

Add the following middleware inside your `app/Http/Kernel.php` file:

```php
protected $routeMiddleware = [
    ...
    'apiguard' => Chrisbjr\ApiGuard\Http\Middleware\ApiGuard::class,
];
```

**Comment by sashahilton00** [comment]
Hi @chrisbjr,

Cheers for that, I am banging my head slightly, should have checked that I had something like that already. That should fix it, will let you know otherwise :)

**Comment by jakeols** [comment]
Hi,

I've been getting the same error. I have added the middleware to my Kernel.php file, but it's still returning the above error.. Any idea what could be causing it?

**Comment by adnanmayo** [comment]
i have installed it from scratch in my project and it is working fine may be it has some conflicts with other package..

**Comment by g011um** [comment]
With Laravel 5.1 I get a ReflectionException using the `$routeMiddleware` line exactly as stated above, and in the README.  I needed to add a leading slash before `Chrisbjr` like this:

```
protected $routeMiddleware = [
    ...
    'apiguard' => \Chrisbjr\ApiGuard\Http\Middleware\ApiGuard::class,
];
```

**Comment by emugabi** [comment]
Fixed this by adding this block to `app/config/apiguard.php`

`'providers'            => [
        'auth' => Chrisbjr\ApiGuard\Providers\Auth\Illuminate::class
    ],`
