### ISSUE TITLE
Error in ApiGuardAuth.php

### ISSUE THREAD

**Issue by jakeols** [chrisbjr/api-guard#114]
Hi,

I recently had no issues up until I upgraded, and am now getting the following error.

ErrorException in ApiGuardAuth.php line 14:
Argument 1 passed to Chrisbjr\ApiGuard\ApiGuardAuth::__construct() must be an instance of Chrisbjr\ApiGuard\Contracts\Providers\Auth, null given, called in 
…vendor\chrisbjr\api-guard\src\Providers\ApiGuardServiceProvider.php on line 49 and defined

I saw that it had been posted before, but adding the middleware did not seem to have any effect. I recently added the laravel auth scaffolding for my application, so I'm not sure if that may have been the cause of the error.

Any help or suggestions would be greatly appreciated!

**Comment by Schnoop** [comment]
You have to check your apiguard.php config file located in the config folder for missing entries.

Just make a diff with the config file located in the vendor folder.

**Comment by chrisbjr** [comment]
Hi @jakeols 

@Schnoop is right - there were quiet a bit of changes in the config file so you'll need to re-publish the config file or copy/paste the missing config variables
