### ISSUE TITLE
Class '\App\User' not found

### ISSUE THREAD

**Issue by sylouuu** [chrisbjr/api-guard#115]
Hi,

I upgraded my app from 5.1 to 5.2. I have the same code as #76.

I have a constructor in my controller.

``` php
    public function __construct(HumanRepository $human_repository)
    {
        parent::__construct();

        $this->human_repository = $human_repository;
    }
```

I have this: `Class '\App\User' not found` but I don't use the built-in user management from Laravel. I've removed all related files (migration, model, controller...).

If I remove `parent::__construct();` it works but no guard is applied.

Bests

**Comment by richdynamix** [comment]
I had the same issue and took me a while to dig in and find the issue. This has two steps - 

Open up the `config/auth.php` file and at line 67 make sure your User model is pointing to the correct model. If you have moved this and updated the namespace, ensure this matches up to your auth model - 

```
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => MyNamespace\Model\User::class,
        ],
```

Once you get this going you will get various errors on authenticating the user model in sessionguard.php. To mitigate this one we need to point api-gaurd to the correct implementation of the authentication contract.

In `config/apiguard.php` on Line 100 change the following - 

```
        'auth' => Chrisbjr\ApiGuard\Providers\Auth\Illuminate::class
```

to - 

```
        'auth' => Chrisbjr\ApiGuard\Providers\Auth\Sentinel::class
```

That is if you are using Sentinel as the authentication provider. API-Gaurd comes with three implementations `Illuminate`, `Sentinel` and `October`. It would probably help if the config docs were updated to make this clear.

If you are using a different method of authentication other that these three then you are free to add your own implementation here. But your authentication must implement `Chrisbjr\ApiGuard\Providers\Auth` to be compliant with the rest of the system.

Hope this helps

**Comment by sylouuu** [comment]
The thing is I don't want to use the built-in model User and all related. So why I have to keep these files? It seems that if you remove it, you can't use Laravel anyway.

**Comment by richdynamix** [comment]
You can use any model you want, you are not forced to use the build in one but you need to update your config to reflect the choice you make. Laravel only expect you to tell it where the authentication is being handled. If you are not using the default then updating the config to match your own should be enough.

**Comment by sylouuu** [comment]
This a project with only one table, no user, no authentication. And you can't remove all this stuff.
