### ISSUE TITLE
Files should end with a empty newline

### ISSUE THREAD

**Issue by Tjoosten** [chrisbjr/api-guard#126]

**Comment by danhunsaker** [comment]
A bold statement, with no supporting commentary.

**Comment by Tjoosten** [comment]
@danhunsaker srry I had a little amount of free time. When I create this issue. There need to be empty new lines. Accordingly to the PSR-2 Standards.

**Comment by danhunsaker** [comment]
Ah. PSR compliance! A fair point.

**Comment by Tjoosten** [comment]
@chrisbjr any update on the PR?
