### ISSUE TITLE
Custom mysql connection for model

### ISSUE THREAD

**Issue by gilbert1995** [chrisbjr/api-guard#13]
hello,
I would like to know if there is a way to change the connection to use mysql for "apikey" and "Apilog" I mean to add the attribute

```php
protected $connection = 'mysql2';
```

In the model of "apikey" and "apilog"

I did not see the opportunity to do so in the code or configuration

thank you very much

**Comment by chrisbjr** [comment]
@gilbert1995 custom ApiKey models can be defined now via the config. Check it out in the develop branch
