### ISSUE TITLE
Pagination 

### ISSUE THREAD

**Issue by snipe** [chrisbjr/api-guard#140]
Hi there - first off, thanks for the great package! I know Laravel Passport makes a lot of the API stuff easier, but I'm stuck on 5.2 for a little while and your package makes life a lot easier.

I did have a quick question - if I want to paginate results, what's the best way to do that? 

So, for example, `https://my.api.blah/api/v1/entries?page=2` or `https://my.api.blah/api/v1/entries?per_page=20&page=2`, using Laravel's built in paginator.

```
$entries = Community::findOrFail($id)->entries()->with('author')->paginate($per_page);
return $this->response->withCollection($entries, new EntriesTransformer);
```

That returns an instance of `Illuminate\Pagination\LengthAwarePaginator`, not an actual model object, which makes the transformer angry. I can obviously change the transformer to:

`public function transform(LengthAwarePaginator $entry)`

but then I have to loop through the collection within the transformer, which feels like the wrong way to do it. Should I write a custom paginator? Am I massively overthinking this?

Any thoughts? Apologies if this has already been discussed or documented. I did check and couldn't find what I was looking for. Thanks in advance!

**Comment by chrisbjr** [comment]
Hi @snipe, sorry haven't been active for a while. You could have used the paginator in the response object like so:

```
$books = Book::paginate();

return $this->response->paginate($books, new BookTransformer);
```

No need to make a custom transformer.

Please note that there is now a v4.

Thanks.
