### ISSUE TITLE
 Does not save log or authenticates when second route parameter is a function

### ISSUE THREAD

**Issue by andreworks** [chrisbjr/api-guard#142]
Hello folks,

I am using the Api guard but just works when route its like this example below

`Route::get('api/v1/books/{id}', 'BooksController@show');`

if a i need to use a route like that

```
Route::get('api/v1/books/{id}', function(){
   
  App::make('App\Http\Controllers\Book\BookController')->getIndex();

});
```

The Api Guard don´t save the log or authenticates.

Someone can help me?

**Comment by chrisbjr** [comment]
Hi, sorry for the late reply. This does not log because you need to use a controller and extend the `ApiGuardController`.

Please note that there is now a v4.
