### ISSUE TITLE
Not working on Laravel 5.4.21

### ISSUE THREAD

**Issue by JanRajtr** [chrisbjr/api-guard#148]
api-guard stopped working on newer versions of Laravel 5.4. I have not changed anything in my code regarding api-guard, controllers, settings etc. It looks like it is never called...
Is there any known issue which prevents use of api-guard?

**Comment by xseguib** [comment]
Any update?

**Comment by JanRajtr** [comment]
I did not try it since the posted message…I believe I will get to it in next weeks…hope it will work magically. -_-

**Comment by chrisbjr** [comment]
Hi all, I currently have a working version on Laravel 5.4. Will push it by
tomorrow.

**Comment by JanRajtr** [comment]
Thank you so much! It would save my life..

26. 5. 2017 v 13:48, Chris Bautista <notifications@github.com>:

> Hi all, I currently have a working version on Laravel 5.4. Will push it by
> tomorrow.
>

**Comment by chrisbjr** [comment]
hi @JanRajtr this is a complete rewrite as Laravel 5.3+ has introduced some things that can be handled "natively" like throttling. Also, api-guard has been converted as a middleware so it can be applied to any route.

**Comment by chrisbjr** [comment]
Hi @JanRajtr v4.0.0 has been tagged. This is a complete rewrite and will only work with 5.3 and 5.4. It is not compatible with previous ApiGuard versions.
