### ISSUE TITLE
KeyAuthentication disabled for version 4.* ?

### ISSUE THREAD

**Issue by simplyrupin** [chrisbjr/api-guard#151]
Hi there,
For earlier versions (3.1.* and below), there was a "keyAuthentication" method implemented in the ApiGuard Middleware that allowed us to override key authentication for certain API's (that are to be called prior to user sign-in). 
I couldn't find a similar feature in version 4.*

Was there any specific reason as to why it was disabled? And what would be the alternative to override key authentication?

Thanks

**Comment by chrisbjr** [comment]
Hi @simplyrupin now that the API key authentication is established in the middleware, you can simply remove the middleware from the specific route that you don't want to have authenticated. 

Let me know if this solves your issue.

**Comment by simplyrupin** [comment]
Hey @chrisbjr Yes, I am already doing that. However, I was wondering if there was a better way to do it at a controller level rather than at the route level.
Thanks for the quick response!
