### ISSUE TITLE
Disappeard api_logs table

### ISSUE THREAD

**Issue by zeshan77** [chrisbjr/api-guard#153]
I installed latest version of api-guard, noticed that `api_logs` table is no longer there and is also deleted from the migration.

Can anyone explain me why was this done?

Thanks

**Comment by hoanglek13** [comment]
> I installed latest version of api-guard, noticed that api_logs table is no longer there and is also deleted from the migration.

> Can anyone explain me why was this done?

> Thanks

I has the same problem so I got nothing when I call this method `$user->apiKeys()`. Some body help me, please

**Comment by jontroncoso** [comment]
Is this something that is going to be reimplemented? I can probably bypass using that `ApiKeyAuthenticated` Event and making my own `api_logs` table/model. But I would prefer using a repo that is going to continue being supported. 


That being said, I noticed you haven't done anything here in 7 months. Is this still being supported? If I create a pull request would you integrate it? Is there a better laravel-way of doing simple (non-oauth) API keys that I'm not seeing?

**Comment by chrisbjr** [comment]
Hi @jontroncoso I have plans on bringing back the api_logs table sometime this month.

This is still being supported but no additional features have been planned yet - asides from bringing back the api logs table.

API keys are used as a special use case and it is now looking like JWT (JSON web tokens) is the preferred way of authenticating APIs nowadays. It provides a more secure way of authenticating APIs and user data can be stored in the tokens.

API keys are static whereas JWTs can be refreshed. You can implement the same for API keys but JWT has a more standard specification.

Some APIs (like Google Maps and many others) still use API keys as their authentication method.
