### ISSUE TITLE
How to give more protettion ?

### ISSUE THREAD

**Issue by msliman** [chrisbjr/api-guard#156]
The problem is the generated key is put statically like:
x-authorization   29060eed4acf341bc595a435674ba9a2a6a17335

So, any body can hack the app and see it so can access any API then ?

Is that logic? and how can overcome this problem ?

**Comment by chrisbjr** [comment]
Hi @msliman to provide more protection, always encrypt your traffic with SSL (HTTPS) and make sure to always store the API key securely.

If you need more protection, consider adding an expiry to the API key.

There are much more "secure" and standard ways to secure APIs like JWT. This package does not aim to replace or be similar to JWT but instead go through the route of providing a basic API authentication by using unique keys.
