### ISSUE TITLE
Issue authorizing via curl

### ISSUE THREAD

**Issue by superbigcreative** [chrisbjr/api-guard#17]
Have you had any issues working locally and doing curl requests with authorization headers?

Here is what I am using:

```
curl --header "Authorization: 2ed9d72e5596800bf805ca1c735e446df72019ef" http://spire.site/api/v1/sites
```

(I went ahead and used the same auth key as your example and updated my key in the test DB so I could quickly past this command in).

I am running the site locally using "spire.site" as my host and not localhost:PORT etc. Could this be the issue? I am hopefully already dealing with the CORS issue as I am using a "laravel-cors" provider to ensure I can get API methods allowed for sharing. 

Is there another way to test the authorization headers / protected methods?

**Comment by superbigcreative** [comment]
It seems that this issue is caused by a known bug with sending specifically the Name "Authorization" with Laravel and Apache.

https://github.com/dingo/api/issues/54

I simply changed the Key in the config to "Key" and passed that in as a header and it worked!

**Comment by chrisbjr** [comment]
@superbigcreative Glad it worked!
