### ISSUE TITLE
Wrong path in v1.0 documentation

### ISSUE THREAD

**Issue by RokSiEu** [chrisbjr/api-guard#31]
In "Using" part of documentation path to ApiGuardController is wrong. Controller folder is missing and you get "ApiGuardController not found" error. 

Regards,
Rok

**Comment by chrisbjr** [comment]
Hi @RokSiEu yeah, i just noticed.

It should be:

`use Chrisbjr\ApiGuard\Controllers\ApiGuardController;`

**Comment by RokSiEu** [comment]
Yup, I just wanted to let you know. This can be closed.
