### ISSUE TITLE
Have you tried with fiddler?

### ISSUE THREAD

**Issue by RokSiEu** [chrisbjr/api-guard#32]
Hi,

did anyone tried to authenticate with fiddler? It works with GET when you send X-Authorization=XXX in URL, but how to do it with POST/PUT/DELETE ? 

I'm testing with fiddler,because I will use this api in android project.

**Comment by chrisbjr** [comment]
try asking in the Gitter channel. Link can be found in the readme

**Comment by RokSiEu** [comment]
So there is no chance to use other requests than GET?

**Comment by chrisbjr** [comment]
All methods are available, of course. Put the "X-Authorization" on the header. Try testing using [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en)

**Comment by chrisbjr** [comment]
Btw, it's never safe to put the "X-Authorization" parameter in the URL. Always put it inside the header. And make sure to always transport with SSL (https) in a live environment.

**Comment by RokSiEu** [comment]
Yes I'm using SSL and trying with Headers, I only tried with parameter in
URL when testing, to see where it goes wrong.

Thank you for Postman tip, didn't know that extension. It solved my
problem.
