### ISSUE TITLE
Info - API limit per User

### ISSUE THREAD

**Issue by ChristianGiupponi** [chrisbjr/api-guard#34]
Hi,
with this package can I set a limit requests for each user or for each type of user?

Example:  
Free account : 1.000requests per day  
Paid account:  10.000 requests per day
Exclusive account: 100.000 requests
and so on

Thanks!

**Comment by chrisbjr** [comment]
Hi @ChristianGiupponi 

You could probably do this yourself within your controller method (or make a middleware). I don't see a way of doing this within the `$apiMethods` variable. You could, however, use the `api_logs` table to check for the number of requests the API key has made.
