### ISSUE TITLE
Models namespace confusion

### ISSUE THREAD

**Issue by gpolguere** [chrisbjr/api-guard#37]
I've just discovered this package and I managed to get it working but I had an issue with Models.
I don't know if I misconfigured anything but I had this exception raised (typo btw) :
> You ApiKey model should be an instance of ApiKeyRepository.

I've noticed you have 2 Models folder with same namespaces for both of the classes ApiKey and ApiLog :
* src/Models
* src/Chrisbjr/ApiGuard/Models

In the autoload_classmap.php that is generated, it takes the 2nd path instead of the 1st one.
Is it normal ? Have I done anything wrong?
Thank you

**Comment by chrisbjr** [comment]
Looks like I forgot to remove the Chrisbjr/* folder. Will fix this. Thanks!

**Comment by phylaxis** [comment]
I'm trying to get this working, but not having any luck and I wonder if it might be because of this issue. Basically for me the requests are not requiring the X-Authorization header. I am still able to hit the API without it. Also logging is enabled but I see no entries in the api_logs table.

**Comment by gpolguere** [comment]
I've forked it and got it working if you want to give a try : https://github.com/MM56/api-guard

**Comment by awkwardusername** [comment]
@gpolguere make it a PR.

**Comment by gpolguere** [comment]
https://github.com/chrisbjr/api-guard/pull/38
