### ISSUE TITLE
Cannot redeclare class CreateApiKeysTable

### ISSUE THREAD

**Issue by MichealMi** [chrisbjr/api-guard#40]
I just started PHP development with Laravel 5 again, so I hope this isn't some kind of beginners mistake.

I installed api-guard as it is described in the instructions. I used to reset the database and add Test data with ```artisan migrate:refresh --seed```. But after installing api-guard it fails with the message:
```
[Symfony\Component\Debug\Exception\FatalErrorException]
Cannot redeclare class CreateApiKeysTable
```
However, using ```artisan migrate``` and ```artisan db:seed``` seperated works.

Is this an actual issue or just my mistake?

**Comment by awkwardusername** [comment]
Does this still happen? I can't seem to figure out how that happened. What version are you using anyway?

**Comment by MichealMi** [comment]
I'm using the 2.2 and the up-to-data Laravel 5. It does still happen:
Doing
```artisan migrate```
```artisan db:seed```
works.

But ```artisan migrate:refresh``` outputs these two errors:

```
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'api_keys_user_i
d_foreign'; check that column/key exists (SQL: alter table `api_keys` drop foreign
key api_keys_user_id_foreign)

[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'api_keys_user_i
d_foreign'; check that column/key exists
```

**Comment by dbonner1987** [comment]
This can be resolved by removing the "database" path from the classmap section in the composer file. I don't think there is any use for it in there as it should only ever be called directly from the app.

```json
"autoload": {
    "psr-4": {
        "Chrisbjr\\ApiGuard\\": "src"
    }
},
```

**Comment by awkwardusername** [comment]
nice catch. thanks @dbonner1987. #60 merged.
