### ISSUE TITLE
Testing Guarded controllers

### ISSUE THREAD

**Issue by goslund** [chrisbjr/api-guard#41]
Hi, I've been working on a project and am implementing functional unit tests with phpunit on laravel 4.2, and I was wondering if you have any hints as to how to get apiguard bootstrapped with the testing framework so I can test against a controller's methods.. Any help would be appreciated!

Thanks,
Geoff

**Comment by ddimaria** [comment]
Hi @goslund, I just added a pull request that got merged related to testing: https://github.com/chrisbjr/api-guard/tree/revamp-laravel5

It's on the L5 branch, but applies to L4.2 as well.

**Comment by goslund** [comment]
Thank you for your response, I'll check it out! :)

Geoff

**Comment by goslund** [comment]
So I know I will need this in just a few steps, but I'm still having
problems. I have inherited a Laravel 4.2 project that utilizes ApiGuard.
The end-points extend ApiGuardControlle, and work in the front end
application, but behind the scenes I am getting errors when I hit the
$this->apiKey->user, and responses, the object is not found (trying to get
property of non-object). I feel like I'm missing something, seeing as how
the key is not being set in my app. Do you have any suggestions?
Geoff

**Comment by goslund** [comment]
Ah. "Route Filters are disabled by default."

**Comment by goslund** [comment]
Er.. Would you not that in your documentation? One needs to
"Route::enableFilters()" before the tests will work.

Thanks!
Geoff

**Comment by ddimaria** [comment]
@goslund, you can just generate a pull request and add this to the L4 readme.

**Comment by goslund** [comment]
Oh, right. :)

**Comment by chrisbjr** [comment]
Closing this
