### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by jayhealey** [chrisbjr/api-guard#43]
I wanted to see if API Guard was Lumen was compatible, and whilst it isn't yet, I think there's a few small tweaks could enable it. I suspect a lot of it is down to class aliases (as they're not included in Lumen) and some dependancies. 

The first step you have to do is uncomment `$app->withFacades();` on line 20 in `app.php`. 

Then the issues are happening when trying to using `artisan` to publish the migration and configurations:
```
Fatal error: Class 'Response' not found in /lumen/vendor/ellipsesynergie/api-response/src/Laravel/ResponseServiceProvider.php on line 29
```

Line 29 is:
```
 \Response::macro('api', function () {
```

I would expect that references Laravel's standard Response facade which is fixed with:
```
\Illuminate\Support\Facades\Response::macro('api', function () { 
```

That appeared to fix it that - but it moved onto another issue when running `artisan`:
```
  [Illuminate\Container\BindingResolutionException]
  Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable.
```

I've yet to resolve what the problem is with this - does anyone else have any ideas?

**Comment by kmgilbert100** [comment]
Would love to see this comparable lumen! Did you have any luck fixing the last issue in your post?

**Comment by vocalogic** [comment]
I'm having this same issue when trying to return a JSON response with the Response facade.

> Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable.

Also, am importing using: 
use Illuminate\Support\Facades\Response;

**Comment by forgottencreature** [comment]
I would also love to see this addressed. I was able to get to the same point. Unable to resolve the instantiable issue. This usually has to do with unregistered service providers, no?

**Comment by kmgilbert100** [comment]
I had to create a api system of my own for a different project of mine so I may turn it into a Lumen "class/extension".

**Comment by jayhealey** [comment]
Sorry I haven't progressed this. I haven't worked with Lumen since this ticket was posted. 

I've ended up using Laravel instead.

**Comment by forgottencreature** [comment]
I was able to get it to a point where it the output was the following error.

PHP Fatal error:  Call to undefined function Chrisbjr\ApiGuard\Providers\config_path() in /var/www/ammo/lumen/vendor/chrisbjr/api-guard/src/Providers/ApiGuardServiceProvider.php on line 28

Lumen doesn't come with support for the config_path() helper function, as far as I'm aware.

**Comment by lahaxearnaud** [comment]
Someone working on this?

**Comment by sylouuu** [comment]
Hi,

What do you think @chrisbjr? I would like to use your work with Lumen but I can't find a better package than api-guard, seems difficult to find an awesome package with a Lumen compatibility.

Bests

**Comment by 0plus1** [comment]
This would be an amazing feature. Laravel has a lot of overhead for a simple json based API.
I might take a look and see what I can do.

**Comment by OskarD** [comment]
@0plus1 any progress? :)

**Comment by jerguslejko** [comment]
@0plus1 Don't really think so. Lumen doesn't even support response macros...

**Comment by chrisbjr** [comment]
@jerguslejko is right - will hold off on this for now

**Comment by yarcowang** [comment]
Upset on this...after adding response macro service in lumen by following the laravel document.
I should say, it seems they are not encouraging using lumen...
