### ISSUE TITLE
TODO: Wiki

### ISSUE THREAD

**Issue by awkwardusername** [chrisbjr/api-guard#46]
Probably, examples and stuff you can do with apiguard should be here. Will be doing when I get more time off my projects. Lol.

But yeah. You can submit PRs and we'll see how it goes. :)

**Comment by kmgilbert100** [comment]
If this was compatible with Lumen so much more could be done!

**Comment by skatcat31** [comment]
seriously getting this thing on lumen would be amazeballs.
Some great examples would be the stateless authentication, limiting a users access to sub resources, denying cruds, accessing MULTIPLE apis with the same key in the same server, touching apikeys to make constant handshakes and keep multiple responses stateless without logins to generate new apikeys for each call(yay handshakes), deleting and undeleting an apikey as a method of logging in and out... Hey is this thing still in need of help?

**Comment by chrisbjr** [comment]
Closing this for now
