### ISSUE TITLE
Missing Guard Implementation in Laravel 5

### ISSUE THREAD

**Issue by cpttripzz** [chrisbjr/api-guard#52]
Maybe I am missing something, but I don't see how this is actually authenticating anything.
This does not work with any authentication middleware even if the api key is attached to a user.

I have hacked the boilerplate L5 authentication middleware to bind to the user attached to the api key like this:

	public function handle($request, Closure $next)
	{

        if($apiKey = $request->headers->get(Config::get('apiguard.keyName'))){
            if($user = $this->userService->getUserByApiKey($apiKey)){
                $this->auth->setUser($user);
            }
        }
		if ($this->auth->guest())
		{
			if ($request->ajax())
			{
				return response('Unauthorized.', 401);
			}
			else
			{
				return redirect()->guest('auth/login');
			}
		}

		return $next($request);
	}

}

Am I being totally dense or does this actually not do any authentication?

**Comment by esseremmerik** [comment]
Hi cpttripzz,

You probably overwritten the __construct function in your controller, somebody else had this as well in a closed issue: https://github.com/chrisbjr/api-guard/issues/33

Hope this helps!
Peter

**Comment by awkwardusername** [comment]
The concept of authentication with api-guard is stateless. See this previous version of README in this commit https://github.com/chrisbjr/api-guard/blob/8bc0fc0046f3334ce5faffef08060e8f624e594c/README.md

**Comment by chrisbjr** [comment]
Closing this
