### ISSUE TITLE
Loging

### ISSUE THREAD

**Issue by cernicc** [chrisbjr/api-guard#53]
Hi.

What if we moved code that gets api key from the header outside of

`if ($keyAuthentication === true) {`

then we could get users api key in request log even if method is turned off for authentication.

**Comment by awkwardusername** [comment]
Err, you might want to reference the code you are talking about and a proper use case so we can understand your issue :)

**Comment by cernicc** [comment]
It's more a feature than an issue :D

https://github.com/chrisbjr/api-guard/pull/54

**Comment by awkwardusername** [comment]
Why would we even need the API key if that method is turned off for `keyAuthentication`?

**Comment by cernicc** [comment]
For the logging. If you want to know which user called a method even if `keyAuthentication` is `false`.
