### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by filipnne** [chrisbjr/api-guard#58]
Hi 
I've installed api-guard with Laravel and coupled it with MongoDB instead of MySQL.
But I've some problem : testing with two different browsers, the authentication not working all the time and some users can pass through it when after the first was authenticated.

There is a configuration not set well or there is a session keep ?

**Comment by bbashy** [comment]
Got some code to reproduce it?

**Comment by chrisbjr** [comment]
Closing this due to insufficient information.
