### ISSUE TITLE
Question: how to send request to http://localhost:8000/api/v1/books

### ISSUE THREAD

**Issue by bautrukevich** [chrisbjr/api-guard#62]
Hello!
Sorry for my dummy question, but can you explain how to send GET request to http://localhost:8000/api/v1/books in controller method to get data?

How to send curl --header "X-Authorization: 2ed9d72e5596800bf805ca1c735e446df72019ef" http://localhost:8000/api/v1/books in controller method in Laravel 5?

May be something like this: 
$response = $this->call('GET', '/api/v1/some-endpoint', [], [], [], ['HTTP_X-Authorization' => 'VALID_TOKEN_HERE']);
but call is not defined : (

Thank you.

**Comment by arkeidolon** [comment]
Hi @bautrukevich, I believe this is what you're looking for: https://github.com/guzzle/guzzle :)

**Comment by bautrukevich** [comment]
@arkeidolon oh, thank you very much!

**Comment by awkwardusername** [comment]
@bautrukevich you can also try http://unirest.io/ for a simpler REST client implementation.

**Comment by bautrukevich** [comment]
@awkwardusername thank's you too!
