### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by forgottencreature** [chrisbjr/api-guard#63]
Is there a more elegant way to throw RESTful error responses via the API for validation within a controller? I don't see anything built in for this in ApiGuardController.

For instance, currently in my store method I'm running validation on the data, then tapping directly into the api-response to output any errors which may have occured.

```php
public function store(Request $request)
{
    $v = \Validator::make($request->all(), [
           'field' => 'required',
    ]);

    if ($v->fails())
    {
        return $this->response->errorWrongArgs($v->errors());
    } 

    $item = new Item;
    $item->field = $request->input('field');
    $item->save();
}
```

**Comment by chrisbjr** [comment]
Hi @forgottencreature 

I guess that's as elegant as it gets. You should be using `errorWrongArgsValidator` instead of `errorWrongArgs` though. Like this:

```
$validator = Validator::make($data, $rules);

if ($validator->fails()) {
    return $this->response->errorWrongArgsValidator($validator);
}
```
