### ISSUE TITLE
get API keys

### ISSUE THREAD

**Issue by clezeraragon** [chrisbjr/api-guard#64]
step as the API key in AJAX or Angle, I'm doing a web application. In postman step Authorization + key and is all right.
but in my application appears 401 (Unauthorized)

**Comment by clezeraragon** [comment]
An example could be angular or ajax

**Comment by AndyWendt** [comment]
@clezeraragon it sounds like it is an issue with your angular or ajax implementation and not this package if it is working in Postman :smiley: 

You may need to provide more clarity and detail to your quest.

**Comment by chrisbjr** [comment]
@AndyWendt has the correct assumption. Closing this.
