### ISSUE TITLE
Setting user from constructor

### ISSUE THREAD

**Issue by kcalliauw** [chrisbjr/api-guard#65]
Hi all,

I've had success setting up the system and it's working quite well. I do have a small problem. I have extended the model (class ApiKey extends ApiKeyRepository) and after adding the relations to the model referring to my users table, getting the user for the API key works fine through this method in the controllers' functions:

    $this->apiKey->user

I would however like to be able to set the user just once in the constructor of the Controller so I can get the authenticated user like $this->user. I've tried adding this to the controller with no success:

    class ServersController extends ApiGuardController
    {
    
        protected $user;
    
        public function __construct()
        {
             parent::__construct();
             $this->user = $this->apiKey->user;
        } 
        ...

Since I'm able to get to this data from any of the functions, I'm wondering why this doesn't seem possible in the constructor. I am likely overlooking something obvious here... When I dump the value of $this->apiKey in the constructor I get null as the value for some reason.

Any help would be very appreciated!

Cheers, 
/K

**Comment by kcalliauw** [comment]
Hey again,

I found the answer to my own question. I had to do this:

    class ServersController extends ApiGuardController
    {
    
        protected $user;

        public function initialize()
        {
            $this->user = $this->apiKey->user;
        }

Cheers,
/K

**Comment by chrisbjr** [comment]
Glad you found this. Overriding the `initialize()` method is really what you should use.
