### ISSUE TITLE
Revoke an API Key

### ISSUE THREAD

**Issue by mansouralex** [chrisbjr/api-guard#66]
What would be the best way to revoke an API key?

**Comment by chrisbjr** [comment]
You can just delete it

**Comment by mansouralex** [comment]
Yes, what if I want to add new column called is_revoked so if it's true then this API key can't access the API, what simple way to do this kind of check on this package. Thanks!

**Comment by chrisbjr** [comment]
Hmm.. You'll have to modify the ApiGuardController for that to work. But really, you should just be deleting the ApiKey. The ApiKey has soft deletes enabled so it really isn't deleted from the database.

**Comment by mansouralex** [comment]
Yes I was thinking of the soft deletes feature to achieve this. Thank you for your quick response.
