### ISSUE TITLE
$this->apiKey->user_id    Trying to get property of non-object

### ISSUE THREAD

**Issue by dschallert** [chrisbjr/api-guard#68]
Hi, since the last update:

    public function initialize()
    {
        // get user matching to supplied apikey
        $user_id = $this->apiKey->user_id;
        $this->user = User::findOrFail($user_id);
        ....
    }

Returns:  Trying to get property of non-object

Is there a new way of accessing the user_id belonging to the api key provided?

thanks

**Comment by dschallert** [comment]
Sorry, it seems to work.

**Comment by KyleMassacre** [comment]
Yeah, this actually didn't work for me. I just did:
```php
$apiKey = ApiKey::where('user_id', '=', $userId)->count();
if ($apiKey >= 1) {
    $overwrite = $this->ask("This user already has an existing API key. Do you want to overwrite it? [y/n]");
    if ($overwrite == 'n') {
        return;
    }
}
```
