### ISSUE TITLE
Unauthorized access on show method

### ISSUE THREAD

**Issue by richdynamix** [chrisbjr/api-guard#7]
When accessing my API via http://url.dev/api/v1/events I am returned with all events as you would expect. This works with and without the API key when using the

`'keyAuthentication' => false,`

However if I try to return just one record with http://url.dev/api/v1/events/3 I get the following even when using the key is switched off:

``{"error":{"code":"GEN-UNAUTHORIZED","http_code":401,"message":"Unauthorized"}}`

My show method -

```
public function show($id)
{
    $event = Ev::find($id);
    if(!$event){
        return Response::api()->errorNotFound('Event Not Found');
    }
    return $this->response->withItem($event, new EventTransformer);
}
```

Any help is appreciated. :) 

Steven

**Comment by r-a-o** [comment]
@awkwardusername which pull request are you referring to? I am using JWT and now I would want api-guard to handle the stateless authentication.
