### ISSUE TITLE
Disable registering of ResponseServiceProvider

### ISSUE THREAD

**Issue by niknetniko** [chrisbjr/api-guard#72]
On line 15 of the ApiGuardServiceProvider there is this line:
```php
$this->app->register('EllipseSynergie\ApiResponse\Laravel\ResponseServiceProvider');
```

However, I already use the api-response package for other api methods that don't need guarding. Since I want to use the JSON:API specification, I had made a custom ResponseServiceProvider for api-response, as instructed [here](https://github.com/ellipsesynergie/api-response/blob/master/src/Laravel/ResponseServiceProvider.php#L41).

My question is if it would be possible to provide a way to not register the ResponseServiceProvider. Perhaps include an option to define if the ResponseServiceProvider should be included or not?

**Comment by chrisbjr** [comment]
Hi @niknetniko sorry for the super duper late response. Have you found any way around this? Closing this issue for now.

**Comment by niknetniko** [comment]
No problem :)

I just use the api-response package bundled with api-guard, which works
fine for me.
Op 24 mrt. 2016 4:35 p.m. schreef "Chris Bautista" <notifications@github.com
