### ISSUE TITLE
Shouldn't I be able to generate a new key within my PHP?

### ISSUE THREAD

**Issue by Arcrammer** [chrisbjr/api-guard#75]
The readme says that I'd generally like to use a new key for each user. How can I do that, though, when they're only created through the command line? Would it be bad to rely on one key for all of my API calls?

**Comment by ellej16** [comment]
+1

**Comment by chrisbjr** [comment]
Hi,

The ApiKey is an Eloquent model so you can always create a new entry like so:

$apiKey = new ApiKey;
$apiKey->key = $apiKey->generateKey();
$apiKey->user_id = xx;
$apiKey->save();

**Comment by Arcrammer** [comment]
Perfect! Thanks, Chris.
