### ISSUE TITLE
No error message if no API key or incorrect one provided

### ISSUE THREAD

**Issue by sylouuu** [chrisbjr/api-guard#76]
Hi @chrisbjr,

I've just installed `api-guard` without issue but I don't have any error message to protect my API.

Here is my controller:

```php
<?php namespace App\Http\Controllers;

use Chrisbjr\ApiGuard\Http\Controllers\ApiGuardController;
use App\Model\Repositories\CollaboratorRepository;

class CollaboratorController extends ApiGuardController {

    private $collaborator_repository;

    public function __construct(CollaboratorRepository $collaborator_repository)
    {
        $this->collaborator_repository = $collaborator_repository;
    }

    public function getAll ()
    {
        $collaborators = $this->collaborator_repository->getAll();

        return response()->json($collaborators);
    }

    public function getById ($id)
    {
        $collaborator = $this->collaborator_repository->getById($id);

        return response()->json($collaborator);
    }

}
```

I get my JSON but I expected errors because I didn't provide the `X-Authorization` header.

I have your 2 tables and generated an API key.

Bests

**Comment by chrisbjr** [comment]
Hi @sylouuu 

The `ApiGuardController` makes use of the `__construct()` method. Your controller currently overrides the `__consturct()` method.

To remedy this, an `initialize()` method was created so you can override that instead of `__construct()`

**Comment by sylouuu** [comment]
Thanks @chrisbjr.

Seems better with: 

```php
    public function __construct(CollaboratorRepository $collaborator_repository)
    {
        parent::__construct();

        $this->collaborator_repository = $collaborator_repository;
    }
```

**Comment by chrisbjr** [comment]
I was thinking of the same thing but wasn't able to suggest it because I was using my phone to reply :) Really glad you figured it out.
