### ISSUE TITLE
does Auth::user()->id get set?

### ISSUE THREAD

**Issue by thedangler** [chrisbjr/api-guard#77]
how would I get the authenticated user id with this API key approach.

I'm trying to make it so that I can use my REST API internally as well as externally.
when using internally the user will be logged in and I'll set the header( I think) unless there is better way to approach this.

**Comment by iateadonut** [comment]
like this?

		$headers = apache_request_headers();
		$api_key = $headers['X-Authorization'];
		
		$user_id = ApiKey::where('key', $api_key)
			->pluck('user_id');
		Auth::loginUsingId($user_id);

**Comment by thedangler** [comment]
Hi, that should work, I can write my own middleware to check for the header or logged in user.
Thank you.

**Comment by chrisbjr** [comment]
Closing this issue
