### ISSUE TITLE
Accessing Facade doesn't seem to work

### ISSUE THREAD

**Issue by brynnbp** [chrisbjr/api-guard#81]
This example doesn't work:

```
$apiKeyGen = new Chrisbjr\ApiGuard\ApiKey;
$newKey = $apiKeyGen->generateKey();
```

It gives a  `[Symfony\Component\Debug\Exception\FatalErrorException] Class 'Chrisbjr\ApiGuard\ApiKey' not found` error.

This works fine (note the extra `\Models` added):

```
$apiKeyGen = new Chrisbjr\ApiGuard\Models\ApiKey;
$newKey = $apiKeyGen->generateKey();
```

Maybe I'm doing something wrong, but thought at least documenting my mistake would be useful to someone in the future. If I made a mistake, maybe in the configuration, can someone point it out?

Thanks.

**Comment by chrisbjr** [comment]
Hi @brynnbp fixed the sample code in the readme to prevent future mistakes. Thanks for pointing it out.
