### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by gholol** [chrisbjr/api-guard#84]
Are you planning supporting 5.2 branch? because beforeFilter() has been removed in Laravel 5.2 so we have to use middlewares right now. I did a quick fork with 5.2 support, but I want to know if I should wait for the "official" update.

**Comment by tuto1902** [comment]
I use this library for several projects and I can't upgrade to Laravel 5.2 without breaking stuff. Any chance of supporting Laravel 5.2 in the near future?

**Comment by gholol** [comment]
You can test my pull request https://github.com/chrisbjr/api-guard/pull/85 in your dev environment and tell me if it works okay for you.
