### ISSUE TITLE
L5.2 upgrade

### ISSUE THREAD

**Issue by ddimaria** [chrisbjr/api-guard#87]
Hi, I just upgraded to L5.2 and pulled the latest apiguard from dev-master.  I'm getting this error: Class apiguard does not exist.  Anyone else getting this?

**Comment by ddimaria** [comment]
I was able to get past this by adding \Chrisbjr\ApiGuard\Http\Middleware\ApiGuard::class to the $middleware in App\Http\Kernel.php

**Comment by ddimaria** [comment]
Resolved this by moving the middleware to the $routeMiddleware attribute:

```protected $routeMiddleware = [
		'auth' => 'App\Http\Middleware\Authenticate',
		'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
		'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',
		'apiguard' => \Chrisbjr\ApiGuard\Http\Middleware\ApiGuard::class,
	];```

**Comment by muya** [comment]
I wrote up a small guide to help with upgrading https://blog.muya.co.ke/api-guard-laravel-5-2/
