### ISSUE TITLE
Input not anymore an alias

### ISSUE THREAD

**Issue by SuperKiwi** [chrisbjr/api-guard#88]
See https://github.com/laravel/laravel/commit/2adbbbd91e9d6e2d569cc56f138b7273efe25651

It could be useful to put full path and not alias because Taylor changes his mind often.

In ApiGuardController and ApiGuard, it is needed to declare the full path for Input : use Illuminate\Support\Facades\Input.

**Comment by ddimaria** [comment]
Alternatively, you can just add this to your aliases array in config/app.php:

**Comment by awkwardusername** [comment]
Can you make PR for this?

**Comment by SuperKiwi** [comment]
Yes I just did one. Do you know if someone managed to make the package work on L5.2 ?
I'm having problems with a T_PAAMAYIM_NEKUDOTAYIM error (which means double colon in Hebrew) line 197 of Middleware\ApiGuard

**Comment by awkwardusername** [comment]
oh. it has been fixed as per 3.0.1
