### ISSUE TITLE
ApiGuard.php line 197 syntax error, unexpected

### ISSUE THREAD

**Issue by gazatem** [chrisbjr/api-guard#89]
Hi,

While testing the package with Laravel 5.1 and 5.2, it has been failed and following message has been thrown:

> FatalErrorException in ApiGuard.php line 197: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)

According to source code, everything is stable. Following line is on line 197 

`$user_id = App::make(Config::get('apiguard.model', 'Chrisbjr\ApiGuard\Models\ApiKey'))::where('key', $api_key)>pluck('user_id');`

**Comment by ddimaria** [comment]
That `::where` is not allowed...would need to be a `->` I think.  It looks like that code was added 15 days ago: https://github.com/chrisbjr/api-guard/commit/076a2b1acd0f47cd7cee5ef4b4163ad798d2d0ef

**Comment by awkwardusername** [comment]
Haha. Sorry about that, would fix. Issue applies to 3.0.0 too so we'll be tagging a new one for update.
