### ISSUE TITLE
Class Chrisbjr\ApiGuard\Http\Middleware\Auth not found

### ISSUE THREAD

**Issue by Rofy87** [chrisbjr/api-guard#92]
I'm using Laravel 5.2 and getting this error Class Chrisbjr\ApiGuard\Http\Middleware\Auth not found
even though i added 'apiguard' to the routeMiddleware

**Comment by ddimaria** [comment]
composer dump-autoload?  If that doesn't work, can you paste your routeMiddleware class?

**Comment by jzho21** [comment]
It seems a when we put "use Auth;" after namespace at Http/Middleware/Apiguard.php will fix this issue.

Do you think that is a bug???

**Comment by gholol** [comment]
Yes, it's a bug.
