### ISSUE TITLE
Undefined index: X-Authorization

### ISSUE THREAD

**Issue by sashahilton00** [chrisbjr/api-guard#93]
Hi,

I have been trying to work out what is going wrong here, I have specified the following in the UserController:

<code>
protected $apiMethods = [
        'userLogin' => [
            'keyAuthentication' => false,
        ],
    ];
</code>

Yet when I call the api endpoint that is assigned to this finction in the controller, I end up with an error like so:

<code>
ErrorException in ApiGuard.php line 196:
Undefined index: X-Authorization
</code>

Am I missing something here, or is this a bug? I'm using Laravel 5.2.

**Comment by ddimaria** [comment]
I know someone made a change that could have affected the parameter passing to the middleware.  Did you add Auto the middleware or routeMIddleware?

**Comment by sashahilton00** [comment]
I added it to the routeMiddleware, I found the problematic code, will submit a PR later, i am now getting a blank response with no error. Will post details when I post the PR this evening

**Comment by sashahilton00** [comment]
Sorted both issues, I have created the PR here: https://github.com/chrisbjr/api-guard/pull/94 hopefully that should fix it.

**Comment by sashahilton00** [comment]
Merged #94
