### ISSUE TITLE
[Not really an issue] User authentication inside ApiGuard middleware

### ISSUE THREAD

**Issue by gholol** [chrisbjr/api-guard#96]
I believe this is related to the #86 pull request.

So I have an forum app written in laravel. While being logged out, I've made some testing API calls and noticed that my user was logged in.

Quick debugging show me it was caused by the ApiGuard middleware.
At the end of the ApiGuard middleware file we have this:

        // login User
        $headers = apache_request_headers();
        $api_key = $headers[Config::get('apiguard.keyName', 'X-Authorization')];

        $user_id = App::make(Config::get('apiguard.model', 'Chrisbjr\ApiGuard\Models\ApiKey'))->where('key', $api_key)
            ->pluck('user_id');

        if($user_id !== 0)
            Auth::loginUsingId($user_id);

So... what's the reasoning behind this and apache dependency? :-) 

Also, it  kinda negates the meaning of API access levels, because no matter what you do if you provide the correct token - BAM user is logged in into the whole app, you can now go back into the main page and access everything.

**Comment by chrisbjr** [comment]
Hi @gholol I've removed this section from the master branch. I'm not sure about this apache dependency but it's redundant to have it placed there.

With that said, the master branch can now accept authentication from multiple resources (taken from tymon's [jwt-auth](https://github.com/tymondesigns/jwt-auth). It accepts authentication from Illuminate, Sentinel, or October. The config file defaults to Illuminate.

Will be updating the readme soon.
