### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by tpharaoh** [chrisbjr/api-guard#99]
Laravel 5.2
    protected $routeMiddleware = [
...
  'apiguard' => \Chrisbjr\ApiGuard\Http\Middleware\ApiGuard::class,
...
    ];

I am getting:
`{"error":{"code":"GEN-METHOD-NOT-ALLOWED","http_code":405,"message":"Method Not Allowed"}}
`
My user was created with --user-id=2

And my curl request is: `curl --header "X-Authorization: 3bbc442956f0092601ab76f788d31bf3c2943bb1" http://localhost:8000/api/v1/tables`

`Route::get('api/v1/tables', 'Api\TablesController@all');
`
and the controller:
```
class TablesController extends ApiGuardController
{
  public function all(Request $request)
    {
        $tables = Tables::all();

      return $this->response->withCollection($tables, new TableTransformer);
	}

}
```

Its pretty much straight from your guide... so what is wrong?

**Comment by gholol** [comment]
It means what it means: `methodNotAllowed` indicates that a route doesn't exist for the HTTP method you are requesting. 

Run `composer dump-autoload` and then  dig into ApiGuard.php middleware and check what `$routeArray` is returning.

**Comment by chrisbjr** [comment]
Hi @tpharaoh looks like your code is ok - which version of ApiGuard are you using? Have you managed to solve the problem?

**Comment by tpharaoh** [comment]
"chrisbjr/api-guard": "^3.0"
I didn't solve it. I was googline around a few days back, but I will get back to it tomorrow.

**Comment by chrisbjr** [comment]
Please use 3.1.x

Thanks

**Comment by g011um** [comment]
Sorry to leave a comment on a closed thread, but I'm experiencing the same issue with Laravel 5.1 and ApiGuard 3.1.1 and wondered if anyone had a fix.  I threw a `dd($routeArray);` into ApiGuard.php (as suggested above) and it indicates routeArray is a 2 element array with empty values:

```
array:2 [
  0 => null
  1 => null
]
```

I was using `Route::resource()` in routes.php, but I also see the same behavior with just Route::get().  I've been using Postman to test, but see the same behavior just in the browser (Chrome).

With Laravel 5.1 I'm wondering if I should drop back to ApiGuard 2.x?
